__author__ = 'Nixon'


class DB:
    NAME = "LeninAudio"

    class COLLECTIONS:
        SONGS = "SONGS"

BUFFERED_TEMP_FILE_PATH = "/tmp/"
BUFFERED_TEMP_FILE_PREFIX = "LENNIN"
BUFFERED_TEMP_LOCATION = BUFFERED_TEMP_FILE_PATH + BUFFERED_TEMP_FILE_PREFIX
BUFFERED_TEMP_FILES = 10


COMMAND_TIMEOUT = 10